<?php

$plugin = array(
  'title' => t('APC Home'),
  'category' => t('Base Three Layouts'),
  'icon' => 'apc_home.png',
  'theme' => 'apc_home',
  'admin css' => '../basethree_layouts_panels_admin.css',
  'regions' => array(
    'top_left' => t('Top Left'),
    'top_right' => t('Top Right'),
    'middle_row' => t('Middle Row'),
    'bottom_left' => t('Bottom Left'),
    'bottom_right' => t('Bottom Right'),
  ),
);
