<?php

$plugin = array(
  'title' => t('Three column 5 4 3 stacked'),
  'category' => t('Bootstrap Panel Layouts'),
  'icon' => '../../layout_icons/threecol_5_4_3_stacked.png',
  'theme' => 'threecol_5_4_3_stacked',
  'admin css' => '../admin-styles.css',
  'regions' => array(
    'header' => t('header'),
    'left' => t('left'),
    'middle' => t('middle'),
    'right' => t('right'),
    'footer' => t('footer'),
  ),
);
