<?php

$plugin = array(
  'title' => t('Two column 7 5 stacked'),
  'category' => t('Bootstrap Panel Layouts'),
  'icon' => '../../layout_icons/twocol_7_5_stacked.png',
  'theme' => 'twocol_7_5_stacked',
  'admin css' => '../bootstrap_panel_layouts_panels_admin.css',
  'regions' => array(
    'header' => t('header'),
    'left' => t('left'),
    'right' => t('right'),
    'footer' => t('footer'),
  ),
);
