<?php

$plugin = array(
  'title' => t('Three Columns Stacked'),
  'category' => t('Bootstrap Panel Layouts'),
  'icon' => 'threecol_4_4_4_stacked.png',
  'theme' => 'threecol_stacked',
  'admin css' => '../bootstrap_panel_layouts_panels_admin.css',
  'regions' => array(
    'top' => t('top'),
    'left' => t('left'),
    'middle' => t('middle'),
    'right' => t('right'),
    'bottom' => t('bottom'),
  ),
);
