<?php

$plugin = array(
  'title' => t('4_8__4_4_4'),
  'category' => t('Bootstrap Panel Layouts'),
  'icon' => '4_8__4_4_4.png',
  'theme' => '4-8--4-4-4',
  'admin css' => '../bootstrap_panel_layouts_panels_admin.css',
  'regions' => array(
    'top_left' => t('Top Left'),
    'top_right' => t('Top Right'),
    'bottom_left' => t('Bottom Left'),
    'bottom_middle' => t('Bottom Middle'),
    'bottom_right' => t('Bottom Right'),
  ),
);
